
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON FINAL NAME START TRANSdfa : start final transitionsstart : START NAMEfinal : FINAL namesnames : names : names NAMEtransitions : transitiontransitions : transitions transitiontransition : TRANS NAME COLON NAME COLON NAMEtransition : TRANS NAME COLON COLON NAME'
    
_lr_action_items = {'START':([0,],[3,]),'$end':([1,7,8,11,18,19,],[0,-1,-6,-7,-9,-8,]),'FINAL':([2,6,],[5,-2,]),'NAME':([3,5,9,10,13,14,16,17,],[6,-4,12,13,-5,15,18,19,]),'TRANS':([4,5,7,8,10,11,13,18,19,],[9,-4,9,-6,-3,-7,-5,-9,-8,]),'COLON':([12,14,15,],[14,16,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dfa':([0,],[1,]),'start':([0,],[2,]),'final':([2,],[4,]),'transitions':([4,],[7,]),'transition':([4,7,],[8,11,]),'names':([5,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dfa","S'",1,None,None,None),
  ('dfa -> start final transitions','dfa',3,'p_dfa','FAParser.py',5),
  ('start -> START NAME','start',2,'p_start','FAParser.py',9),
  ('final -> FINAL names','final',2,'p_final','FAParser.py',13),
  ('names -> <empty>','names',0,'p_names_1','FAParser.py',17),
  ('names -> names NAME','names',2,'p_names_2','FAParser.py',21),
  ('transitions -> transition','transitions',1,'p_transitions_1','FAParser.py',25),
  ('transitions -> transitions transition','transitions',2,'p_transitions_2','FAParser.py',29),
  ('transition -> TRANS NAME COLON NAME COLON NAME','transition',6,'p_transition_1','FAParser.py',33),
  ('transition -> TRANS NAME COLON COLON NAME','transition',5,'p_transition_2','FAParser.py',37),
]
